[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  :let g:deoplete#enable_at_startup = 0
  let g:deoplete#auto_completion_start_length = 2
  set completeopt+=noinsert
  function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction"}}}
  inoremap <silent><expr> <TAB>
	\ pumvisible() ? "\<C-n>" :
	\ <SID>check_back_space() ? "\<TAB>" :
	\ deoplete#manual_complete()
'''

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  autocmd FileType denite call s:denite_my_settings()
  function! s:denite_my_settings() abort
    nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    " filtering ウィンドウを開く
    nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
    " 削除
    nnoremap <silent><buffer><expr> d
    \ denite#do_map('do_action', 'delete')
    " Denite を閉じる
    nnoremap <silent><buffer><expr> q       denite#do_map('quit')
  endfunction

  call denite#custom#var('file/rec', 'command',
  \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  noremap <Space>f :Denite file/rec<CR>

  call denite#custom#var('grep', 'command', ['ack'])
  call denite#custom#var('grep', 'default_opts',
		  \ ['--ackrc', $HOME.'/.ackrc', '-H',
		  \  '--nopager', '--nocolor', '--nogroup', '--column'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--match'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])
  noremap <Space>gl :Denite grep<CR>
'''

# 履歴
[[plugins]]
repo = 'Shougo/neomru.vim'
hook_add = '''
  noremap <Space>uz :Denite file_mru<CR>
'''

# yank 履歴
[[plugins]]
repo = 'Shougo/neoyank.vim'
hook_add = '''
  noremap <Space>y :Denite neoyank<CR>
'''

[[plugins]]
repo = '5t111111/denite-rails'
hook_add = '''
  nnoremap <Space>v  :<C-U>Denite rails:view<CR>
  nnoremap <Space>m  :<C-U>Denite rails:model<CR>
  nnoremap <Space>c  :<C-U>Denite rails:controller<CR>
  nnoremap <Space>s  :<C-U>Denite rails:spec<CR>
'''

[[plugins]]
repo = 'himanoa/denite-git-grep'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# Git vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <Space>gb :<C-u>Gblame<Enter>
  nnoremap <Space>gs :<C-u>Gstatus<Enter>
  nnoremap <Space>gd :<C-u>Gdiff<Enter>
'''

# vim-rails
[[plugins]]
repo = 'tpope/vim-rails'
hook_add = '''
  nnoremap <Space>rr :R<CR>
  nnoremap <Space>rs :RS<CR>
  nnoremap <Space>rv :RV<CR>
  " spec と application を切り替える
  nnoremap <Space>aa :A<CR>
  nnoremap <Space>as :AS<CR>
  nnoremap <Space>av :AV<CR>
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  " コメントアウトのあとにスペースを挿入
  " cc でコメントアウト
  nmap cc <Plug>NERDCommenterToggle
  vmap cc <Plug>NERDCommenterToggle

  let g:NERDSpaceDelims = 1
'''

# 行末の半角スペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rbenv'

[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_fixers = {
  \   'ruby': ['rubocop'],
  \}
  nnoremap <Space>af :ALEFix<CR>
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'wakatime/vim-wakatime'
